"""create initial portfolio tables

Revision ID: e299a86cbfe5
Revises: 
Create Date: 2026-04-04 13:28:58.839761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e299a86cbfe5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(length=100), nullable=False),
    sa.Column('account_label', sa.String(length=100), nullable=False),
    sa.Column('market_scope', sa.String(length=20), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('data_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_issues_id'), 'data_issues', ['id'], unique=False)
    op.create_table('fx_rate_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('rate_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rate_snapshots_id'), 'fx_rate_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_fx_rate_snapshots_rate_timestamp'), 'fx_rate_snapshots', ['rate_timestamp'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_id'), 'price_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_price_timestamp'), 'price_snapshots', ['price_timestamp'], unique=False)
    op.create_index(op.f('ix_price_snapshots_symbol'), 'price_snapshots', ['symbol'], unique=False)
    op.create_table('sector_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_mappings_id'), 'sector_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_sector_mappings_symbol'), 'sector_mappings', ['symbol'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_id'), 'sync_runs', ['id'], unique=False)
    op.create_table('cash_balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_native', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('amount_base', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_balance_snapshots_account_id'), 'cash_balance_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_cash_balance_snapshots_id'), 'cash_balance_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_cash_balance_snapshots_snapshot_time'), 'cash_balance_snapshots', ['snapshot_time'], unique=False)
    op.create_table('holding_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('security_name', sa.String(length=200), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('sleeve', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_cost_native', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('current_price_native', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('cost_basis_native', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('market_value_native', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unrealized_pnl_native', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unrealized_return_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('cost_basis_base', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('market_value_base', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unrealized_pnl_base', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_snapshots_account_id'), 'holding_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_holding_snapshots_id'), 'holding_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_holding_snapshots_snapshot_time'), 'holding_snapshots', ['snapshot_time'], unique=False)
    op.create_index(op.f('ix_holding_snapshots_symbol'), 'holding_snapshots', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holding_snapshots_symbol'), table_name='holding_snapshots')
    op.drop_index(op.f('ix_holding_snapshots_snapshot_time'), table_name='holding_snapshots')
    op.drop_index(op.f('ix_holding_snapshots_id'), table_name='holding_snapshots')
    op.drop_index(op.f('ix_holding_snapshots_account_id'), table_name='holding_snapshots')
    op.drop_table('holding_snapshots')
    op.drop_index(op.f('ix_cash_balance_snapshots_snapshot_time'), table_name='cash_balance_snapshots')
    op.drop_index(op.f('ix_cash_balance_snapshots_id'), table_name='cash_balance_snapshots')
    op.drop_index(op.f('ix_cash_balance_snapshots_account_id'), table_name='cash_balance_snapshots')
    op.drop_table('cash_balance_snapshots')
    op.drop_index(op.f('ix_sync_runs_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_sector_mappings_symbol'), table_name='sector_mappings')
    op.drop_index(op.f('ix_sector_mappings_id'), table_name='sector_mappings')
    op.drop_table('sector_mappings')
    op.drop_index(op.f('ix_price_snapshots_symbol'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_price_timestamp'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_fx_rate_snapshots_rate_timestamp'), table_name='fx_rate_snapshots')
    op.drop_index(op.f('ix_fx_rate_snapshots_id'), table_name='fx_rate_snapshots')
    op.drop_table('fx_rate_snapshots')
    op.drop_index(op.f('ix_data_issues_id'), table_name='data_issues')
    op.drop_table('data_issues')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
